language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '7'
  - '6'
  - '4'

install:
  - yarn install --no-progress

script:
  - yarn run test:coverage

after_success:
  - >
    if [ $TRAVIS_BRANCH = 'master' ];
    then
      yarn run semantic-release
    fi

  - yarn run test:report